api/urls.py
import api.swagger as s
from django.urls import path, include
from rest_framework import routers
from api.views import NewsList

router = routers.DefaultRouter()
router.register('news', NewsList)

urlpatterns = [
    path('api/', include(router.urls)),
    path('swagger/', s.schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
]

news/urls.py
from django.urls import path
from django.conf.urls import url
from django.contrib.auth.views import LoginView
from . import views


urlpatterns = [
    path('', views.NewsView.as_view(), name='index'),
    url(r'^users/login/$', LoginView.as_view(template_name='users/login.html'), name='login'),
    url(r'^accounts/logout/$', views.logout_view, name='logout'),
    url(r'^register/$', views.register, name='register'),
]

news_agregator/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include

urlpatterns = [
    path('admin/', admin.site.urls),
    url('', include(('news.urls', 'news'), namespace='news')),
    url('', include(('api.urls', 'api'), namespace='api')),
]

api/models.py
from django.db import models

# Create your models here.

news/models.py
from django.db import models
from datetime import datetime


# Create your models here.
class Sources(models.Model):
    source_id = models.AutoField(primary_key=True)
    source_name = models.CharField(max_length=255)


class Categories(models.Model):
    category_id = models.AutoField(primary_key=True)
    category_name = models.CharField(max_length=255)


class News(models.Model):
    news_id = models.AutoField(primary_key=True)
    source = models.ForeignKey(Sources, on_delete=models.CASCADE, db_column='source_id', default=0)
    link = models.CharField(max_length=255)
    category = models.ForeignKey(Categories, on_delete=models.CASCADE, db_column='category_id', default=0)
    title = models.TextField()
    date = models.FloatField(default=datetime.now().timestamp())

api/views.py
from rest_framework.permissions import IsAuthenticated
from api.serializer import NewsSerializer
from news.models import News
from rest_framework.viewsets import ReadOnlyModelViewSet


# Create your views here.

class NewsList(ReadOnlyModelViewSet):
    permission_classes = [IsAuthenticated]
    queryset = News.objects.all()
    serializer_class = NewsSerializer

news/views.py
from django.contrib.auth import logout, authenticate, login
from django.contrib.auth.forms import UserCreationForm
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.views.generic.base import TemplateView
from news.models import News, Sources
from django.shortcuts import get_object_or_404


# Create your views here.
class NewsView(TemplateView):

    template_name = "index.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        onliner = get_object_or_404(Sources, source_name="onliner.by")
        tut = get_object_or_404(Sources, source_name="tut.by")
        context['onliner'] = News.objects.filter(source_id=onliner.source_id).order_by("-date")[:25]
        context['tut'] = News.objects.filter(source_id=tut.source_id).order_by("-date")[:20]
        return context


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(request.META['HTTP_REFERER'])


def register(request):
    if request.method != 'POST':
        form = UserCreationForm()
    else:
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            new_user = form.save()
            authenticated_user = authenticate(username=new_user.username,
                                              password=request.POST['password1'])
            login(request, authenticated_user)
            return HttpResponseRedirect(reverse('news:index'))
    context = {'form': form}
    return render(request, 'users/register.html', context)

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>MyNews</title>
    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
</head>
<body>
{% block header %}
<!-- NavBar -->
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <div class="container">
        <a class="navbar-brand" href="/">
            <img src="http://127.0.0.1:8000/static/logo.png" width="200" height="50"
                 alt="" loading="lazy">
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
             <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link" href="https://www.onliner.by">Onliner.by</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="https://unblockproxy.me/index.php?q=n6XYoqltYmGlnqqjY9udpqLDnqhimtRlb6fUp9ajqM-klg">TUT.by</a>
                </li>
                 <li class="nav-item">
                    <a class="nav-link" href="/api/news/">API</a>
                </li>
                 <li class="nav-item">
                    <a class="nav-link" href="/swagger/">API documentation</a>
                </li>
            </ul>
             {% if user.is_authenticated %}
            <a href="{% url 'news:logout' %}" type="button" class="btn btn-outline-light me-2">
                @{{ user.username }}, logout?
            </a>
            {% else %}
            <a href="{% url 'news:register' %}" type="button" class="btn btn-outline-light me-2">
                Sign up
            </a>
            <a href="{% url 'news:login' %}" type="button" class="btn btn-outline-light me-2">
                Sign in
            </a>
            {% endif %}
        </div>
    </div>
</nav>
<!-- End NavBar -->
{% endblock header %}
{% block content %}
<main class="container">
    <div class="starter-template text-center py-5 px-3">
        {% block main %}
        {% endblock main %}
        {% block footer %}
    <!-- Footer -->
        <footer class="footer">
            <nav class="navbar fixed-bottom navbar-dark bg-primary">
                <div class="container">
                    <font color="#f0ffff">© 2021 Andrei Lukin</font>
                </div>
            </nav>
        </footer>
        <!-- End footer -->
        {% endblock footer %}
    </div>
</main>
{% endblock content %}
</body>
</html>

templates/index.html
{% extends "base.html" %}
{% block main %}
  <div class="row justify-content-center">
    <div class="col-6" align="justify">
        <h1 align="center">onliner.by</h1>
        {% for post in onliner %}
            <ul><a href="{{ post.link }}">{{ post.title }}</a></ul>
        {% endfor %}
    </div>
    <div class="col-6" align="justify">
      <h1 align="center">TUT.by</h1>
        {% for post in tut %}
            <ul><a href="{{ post.link }}">{{ post.title }}</a></ul>
        {% endfor %}
    </div>
  </div>

{% endblock main%}

templates/users/login.html
{% extends "base.html" %}
{% load bootstrap5 %}
{% block main %}
<h1  align="left">Log in to your account.</h1>
<div class="row">
    <div class="col-sm-6" align="left">
        <form method="post" action="{% url 'news:login' %}" class="form">
            {% csrf_token %}
            {% bootstrap_form form %}
            {% buttons %}
            <button name="submit" class="btn btn-outline-primary">log in</button>
            {% endbuttons %}
            <input type="hidden" name="next" value="{{request.META.HTTP_REFERER}}" />
        </form>
    </div>
</div>
{% endblock main %}

templates/users/register.html
{% extends "base.html" %}
{% load bootstrap5 %}
{% block main %}
<h1 align="left"> Registration form </h1>
<div class="row">
    <div class="col-sm-6" align="left">
        <form method="post" action="{% url 'news:register' %}" class="form">
            {% csrf_token %}
            {% bootstrap_form form %}
            {% buttons %}
                <button name="submit" class="btn btn-outline-primary">
                    Sign up
                </button>
            {% endbuttons %}
            <input type="hidden" name="next" value="{% url 'news:index' %}" />
        </form>
    </div>
</div>
{% endblock main %}